session_name: Bun Playground
suppress_history: false
windows:
    - window_name: Git
      panes:
          - shell_command:
                - git fetch
                - lazygit

    - window_name: Main
      layout: even-horizontal
      panes:
          - shell_command: ${EDITOR} -S
            focus: true
          - bun run dev
