session_name: Bun Playground
suppress_history: false
windows:
    - panes:
          - bun run dev
    - panes:
          - ${EDITOR} -S
    - panes:
          - shell_command:
                - git fetch
                - git status
